### PR TITLE
Enhance VerifiedDoubles cop

### PR DESCRIPTION
**Pull request by andyw8**
This replaces #87 which was accidentally closed.

### CODE REVIEW

**Comment by nijikon** [comment]
@andyw8 do we want ```IgnoreSymbolicName``` be ```true``` by default?

**Comment by andyw8** [comment]
@nijikon I believe so, for the reasons mentioned by @CJBridges in #35 and #36.

**Comment by CJBridges** [comment]
I'll be using the option, but I suggest defaulting it to "false" so the cop defaults to its strongest state and behaves obviously.  The rule with its subtleties can be turned on intentionally.

**Comment by andyw8** [comment]
Ok, I've updated the PR to remove that default.

**Comment by nijikon** [comment]
@andyw8 please rebase on top of master

**Comment by andyw8** [comment]
I'll do this after #85 is merged, otherwise I think one of these will end up conflicted again.

**Comment by nijikon** [comment]
@andyw8 done, rebase please

**Comment by andyw8** [comment]
@nijikon rebased.

**Pull request merged**
