### PR TITLE
Focused Specs: `:focus`

### PR DESCRIPTION
**Pull request by jaredmoody**
Builds on #74 to also check for `:focus`. I'm very unfamiliar with rubocop internals, so I could use some eyes on this.

### CODE REVIEW

**Comment by olliebennett** [comment]
:+1: This would be really helpful, and would replace my hacked together git hook I currently use for this!

**Comment by renanborgescampos** [comment]
:+1:

**Comment by nijikon** [comment]
@jaredmoody  Thanks for your contribution. Can you rebase this on top of master?

**Comment by nijikon** [comment]
Also please add a CHANGELOG message.

**Pull request merged**
