### PR TITLE
 Add NotToNot cop

### PR DESCRIPTION
**Pull request by miguelfteixeira**
The NotToNot cop enforces the usage of the same method on all negative message expectations.

The cop can be configured to accept the `not_to` or the `to_not` method by setting the `AcceptedMethod` option.

### CODE REVIEW

**Comment by andyw8** [comment]
Nice idea!

**Comment by nijikon** [comment]
@miguelfteixeira Please rebase on top of master

**Comment by miguelfteixeira** [comment]
@nijikon Done

**Comment by nijikon** [comment]
@miguelfteixeira Can you please rebase again? Sorry for the inconvenience.

**Comment by nijikon** [comment]
Also please add a changelog entry.

**Comment by miguelfteixeira** [comment]
@nijikon changelog updated and branch rebased.

**Comment by nijikon** [comment]
@miguelfteixeira please fix tests :)

**Comment by miguelfteixeira** [comment]
@nijikon sorry, didn't notice the tests were fixed, awesome!
All green and ready to merge :)

**Pull request merged**
