### PR TITLE
Drop support for Ruby 2.0

### PR DESCRIPTION
**Pull request by backus**

### CODE REVIEW

**Comment by bbatsov** [comment]
I believe you meant to say 2.0. :-) For what is worth RuboCop will continue supporting 2.0 for a while.

**Comment by backus** [comment]
@bbatsov whoops thanks for catching that.

> For what is worth RuboCop will continue supporting 2.0 for a while.

Yeah I considered matching what RuboCop supports but the maintenance of this gem has been someone lacking so I figured it would make it easier (if it is mainly just me) to reduce to number of versions I support.

**Comment by andyw8** [comment]
I guess this means all the magic encoding comments can be removed?

**Comment by backus** [comment]
> I guess this means all the magic encoding comments can be removed?

Good catch yeah I'll remove them

**Pull request merged**
