### PR TITLE
Add SubjectStub cop

### PR DESCRIPTION
**Pull request by backus**

### CODE REVIEW

**Comment by backus** [comment]
@andyw8 not ready for prime time at all but this should give you an idea of the bare minimum complexity for a cop like this

**Comment by backus** [comment]
I think this is actually pretty stable now. Running this against a lot of local projects yielded good results.

**Comment by andyw8** [comment]
@turino As this PR is already merged, would you mind creating an issue for these enhancements? I agree they'd both be useful.

**Comment by turino** [comment]
@andyw8 I'd be happy to

**Pull request merged**
